# Generated by Django 4.1 on 2022-09-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_universidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='profecion',
            new_name='profesion',
        ),
    ]
